
sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
            
            
sonata_admin:
    options:
        default_admin_route: edit
        skin: 'skin-black'